version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      - PG_DATA:/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: